#
# Makefile for the nubia drivers.
#

obj-$(CONFIG_NUBIA_NFC)     	+= nfc/
obj-$(CONFIG_NUBIA_SENSORS)			+=sensors/
obj-$(CONFIG_NUBIA_TOUCHSCREENS)      += touch/
obj-$(CONFIG_NUBIA_HW_VERSION)			+=hw_version/
obj-$(CONFIG_NUBIA_FINGERPRINT)       += fingerprint/

